[default]
opaque_types = ["FndrOpaqueInfo", "HFSCatalogFolder", "HFSPlusCatalogFolder", "HFSCatalogFile", "HFSPlusCatalogFile"]
replacements = [
    "pub type id = NSUnit; #=># ",
    "pub type id = *mut u64; #=># ",
    "pub trait NSImage_: Sized + std::ops::Deref {} #=># ",
    "timezone: NSTimeZone, #=># timezone_: NSTimeZone,",
    "componentsInTimeZone : timezone #=># componentsInTimeZone : timezone_",
    "cString: *const ::std::os::raw::c_char, #=># c_string: *const ::std::os::raw::c_char,",
    "stringWithCString : cString #=># stringWithCString : c_string",
]
[Photos]
replacements = [
    "pub type id = PHObject; #=># ",
]
[SyncServices]
replacements = [
    """formattedRecord: NSDictionary,
        recordId: NSString, #=># formattedRecord: NSDictionary,
        recordId2: NSString,""",
    "newRecordIdentifier : recordId #=># newRecordIdentifier : recordId2",
]
