name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose --features AGL,AVFAudio,AVFoundation,Accelerate,Accessibility,Accounts,AdServices,AdSupport,AppTrackingTransparency,AppleScriptObjC,ApplicationServices,AudioToolbox,AudioUnit,AudioVideoBridging,AutomaticAssessmentConfiguration,BackgroundTasks,CFNetwork,CHIP,CallKit,Carbon,ClassKit,CloudKit,ColorSync,Contacts,CoreAudio,CoreBluetooth,CoreData,CoreFoundation,CoreGraphics,CoreHaptics,CoreImage,CoreLocation,CoreMIDI,CoreML,CoreMedia,CoreMediaIO,CoreMotion,CoreServices,CoreSpotlight,CoreTelephony,CoreText,CoreVideo,CoreWLAN,CryptoTokenKit,DVDPlayback,DataDetection,DeviceCheck,DirectoryService,DiscRecording,DiskArbitration,EventKit,ExceptionHandling,ExecutionPolicy,ExposureNotification,ExternalAccessory,FWAUserLib,FileProvider,FileProvider,ForceFeedback,Foundation,GLKit,GLUT,GSS,GameController,Hypervisor,ICADevices,IMServicePlugIn,IOBluetooth,IOKit,IOSurface,IOUSBHost,IdentityLookup,ImageIO,InstantMessage,Intents,JavaScriptCore,Kerberos,KernelManagement,LDAP,LatentSemanticMapping,LocalAuthentication,MLCompute,MediaAccessibility,MediaLibrary,MediaPlayer,MediaToolbox,Metal,MetricKit,ModelIO,NaturalLanguage,NearbyInteraction,NetFS,Network,NetworkExtension,OSLog,OpenAL,OpenCL,OpenDirectory,OpenGL,PCSC,PHASE,Photos,PushKit,QuartzCore,QuickLook,QuickLookThumbnailing,ScriptingBridge,Security,SecurityFoundation,SensorKit,ServiceManagement,ShazamKit,SoundAnalysis,Speech,SyncServices,SystemConfiguration,SystemExtensions,TWAIN,Tcl,UniformTypeIdentifiers,UserNotifications,VideoDecodeAcceleration,VideoSubscriberAccount,VideoToolbox,Vision,WidgetKit,iTunesLibrary,vmnet
